baseURL = 'https://anand-raj.github.io/cms-hugo-decap/'
languageCode = 'en-us'
title = 'My New Hugo Project'

[params]
  description = "A production-ready Hugo site built with best practices."

  [params.social]
    twitter = "yourtwitterhandle"
    github  = "anand-raj"
